version: "3"
services:
  web:
    container_name: backend_flask
    build: .
    restart: on-failure
    depends_on:
      - db
    environment:
      FLASK_DEBUG: ${FLASK_DEBUG}
    ports:
      - "8000:5000"
    volumes:
      - .:/src
  db:
    container_name: backend_postgres
    image: postgres:latest
    restart: always
    ports:
        - "5428:5432"
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: postgres_db
    volumes:
        - postgres_data:/var/datadb/

  pgadmin-compose:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "16543:80"
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
